collections:
  authors:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap


title: George Richardson
description: George Richardson is a Stage Manager, Theatre Technician, and occasional Web and App Developer based in Melbourne, Australia.
thumbnail: /assets/images/headshot-resized.jpg
url: https://grichardson.com.au
email: grrichardson15@gmail.com